# Runs each topology on all environments.
topology_paths = [
  "example-topologies/canonical.yaml",
]

environments = [
  "ISTIO",
]

[cluster]
project_id = "ymzhu-istio"
# Cluster will be created with one n1-standard-1 node in the default node-pool
# running Prometheus. In total, the cluster will have 1 Prometheus node, 1
# client node, and N service-graph nodes (total of N + 2 nodes).
name = "rbac-perf-test-2"
zone = "us-east1-b"
version = "1.9.7-gke.11"

[istio]
archive_url = "https://github.com/istio/istio/releases/download/1.0.3/istio-1.0.3-linux.tar.gz"

[server]
machine_type = "n1-standard-2"
disk_size_gb = 16
num_nodes = 4
image = "tahler/isotope-service:1"

[client]
machine_type = "n1-standard-8"
disk_size_gb = 16
# Necessary fork to allow Fortio's server to output Prometheus metrics.
image = "tahler/fortio:prometheus"
# "max" is a special string, otherwise use a number.
qps = "max"
duration = "5m"
num_concurrent_connections = 64
